# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'readprap.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_readpcap(object):
    def setupUi(self, readpcap):
        readpcap.setObjectName("readpcap")
        readpcap.resize(691, 826)
        self.pcapudp = QtWidgets.QCheckBox(readpcap)
        self.pcapudp.setGeometry(QtCore.QRect(230, 105, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapudp.setFont(font)
        self.pcapudp.setObjectName("pcapudp")
        self.pcapdstipread = QtWidgets.QLineEdit(readpcap)
        self.pcapdstipread.setGeometry(QtCore.QRect(510, 135, 171, 24))
        self.pcapdstipread.setObjectName("pcapdstipread")
        self.pcapsend = QtWidgets.QPushButton(readpcap)
        self.pcapsend.setGeometry(QtCore.QRect(270, 785, 161, 34))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pcapsend.setFont(font)
        self.pcapsend.setObjectName("pcapsend")
        self.pcapsrcport = QtWidgets.QCheckBox(readpcap)
        self.pcapsrcport.setGeometry(QtCore.QRect(10, 165, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapsrcport.setFont(font)
        self.pcapsrcport.setObjectName("pcapsrcport")
        self.pcaparp = QtWidgets.QCheckBox(readpcap)
        self.pcaparp.setGeometry(QtCore.QRect(430, 105, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcaparp.setFont(font)
        self.pcaparp.setObjectName("pcaparp")
        self.pcapsrcportread = QtWidgets.QLineEdit(readpcap)
        self.pcapsrcportread.setGeometry(QtCore.QRect(140, 165, 171, 24))
        self.pcapsrcportread.setObjectName("pcapsrcportread")
        self.pcapdstportread = QtWidgets.QLineEdit(readpcap)
        self.pcapdstportread.setGeometry(QtCore.QRect(510, 165, 171, 24))
        self.pcapdstportread.setObjectName("pcapdstportread")
        self.pcaptcp = QtWidgets.QCheckBox(readpcap)
        self.pcaptcp.setGeometry(QtCore.QRect(140, 105, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcaptcp.setFont(font)
        self.pcaptcp.setObjectName("pcaptcp")
        self.pcapfilechoose = QtWidgets.QPushButton(readpcap)
        self.pcapfilechoose.setGeometry(QtCore.QRect(590, 15, 31, 24))
        self.pcapfilechoose.setObjectName("pcapfilechoose")
        self.pcapseqnum = QtWidgets.QLineEdit(readpcap)
        self.pcapseqnum.setGeometry(QtCore.QRect(360, 485, 81, 31))
        self.pcapseqnum.setObjectName("pcapseqnum")
        self.pcapdstip = QtWidgets.QCheckBox(readpcap)
        self.pcapdstip.setGeometry(QtCore.QRect(360, 135, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapdstip.setFont(font)
        self.pcapdstip.setObjectName("pcapdstip")
        self.pcapfilter = QtWidgets.QPushButton(readpcap)
        self.pcapfilter.setGeometry(QtCore.QRect(240, 235, 221, 34))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pcapfilter.setFont(font)
        self.pcapfilter.setObjectName("pcapfilter")
        self.pcaptodisplay = QtWidgets.QPushButton(readpcap)
        self.pcaptodisplay.setGeometry(QtCore.QRect(440, 485, 111, 31))
        self.pcaptodisplay.setObjectName("pcaptodisplay")
        self.pcapip = QtWidgets.QCheckBox(readpcap)
        self.pcapip.setGeometry(QtCore.QRect(70, 105, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapip.setFont(font)
        self.pcapip.setObjectName("pcapip")
        self.label_4 = QtWidgets.QLabel(readpcap)
        self.label_4.setGeometry(QtCore.QRect(10, 95, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(readpcap)
        self.label.setGeometry(QtCore.QRect(20, 5, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pcapdstport = QtWidgets.QCheckBox(readpcap)
        self.pcapdstport.setGeometry(QtCore.QRect(360, 165, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapdstport.setFont(font)
        self.pcapdstport.setObjectName("pcapdstport")
        self.pcapsrcipread = QtWidgets.QLineEdit(readpcap)
        self.pcapsrcipread.setGeometry(QtCore.QRect(140, 135, 171, 24))
        self.pcapsrcipread.setObjectName("pcapsrcipread")
        self.pcapdata = QtWidgets.QCheckBox(readpcap)
        self.pcapdata.setGeometry(QtCore.QRect(10, 195, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapdata.setFont(font)
        self.pcapdata.setObjectName("pcapdata")
        self.pcapicmp = QtWidgets.QCheckBox(readpcap)
        self.pcapicmp.setGeometry(QtCore.QRect(320, 105, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapicmp.setFont(font)
        self.pcapicmp.setObjectName("pcapicmp")
        self.label_2 = QtWidgets.QLabel(readpcap)
        self.label_2.setGeometry(QtCore.QRect(20, 55, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pcapfilename = QtWidgets.QLineEdit(readpcap)
        self.pcapfilename.setGeometry(QtCore.QRect(110, 15, 481, 24))
        self.pcapfilename.setObjectName("pcapfilename")
        self.pcapsrcip = QtWidgets.QCheckBox(readpcap)
        self.pcapsrcip.setGeometry(QtCore.QRect(10, 135, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pcapsrcip.setFont(font)
        self.pcapsrcip.setObjectName("pcapsrcip")
        self.label_3 = QtWidgets.QLabel(readpcap)
        self.label_3.setGeometry(QtCore.QRect(70, 480, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pcapdataread = QtWidgets.QTextEdit(readpcap)
        self.pcapdataread.setGeometry(QtCore.QRect(140, 193, 541, 31))
        self.pcapdataread.setObjectName("pcapdataread")
        self.pcapdisplaydigest = QtWidgets.QTextEdit(readpcap)
        self.pcapdisplaydigest.setGeometry(QtCore.QRect(10, 280, 671, 191))
        self.pcapdisplaydigest.setObjectName("pcapdisplaydigest")
        self.pcapdisplay = QtWidgets.QTextEdit(readpcap)
        self.pcapdisplay.setGeometry(QtCore.QRect(10, 520, 671, 251))
        self.pcapdisplay.setObjectName("pcapdisplay")

        self.retranslateUi(readpcap)
        QtCore.QMetaObject.connectSlotsByName(readpcap)

    def retranslateUi(self, readpcap):
        _translate = QtCore.QCoreApplication.translate
        readpcap.setWindowTitle(_translate("readpcap", "Form"))
        self.pcapudp.setText(_translate("readpcap", "UDP"))
        self.pcapsend.setText(_translate("readpcap", "发送数据包"))
        self.pcapsrcport.setText(_translate("readpcap", "源端口"))
        self.pcaparp.setText(_translate("readpcap", "ARP"))
        self.pcaptcp.setText(_translate("readpcap", "TCP"))
        self.pcapfilechoose.setText(_translate("readpcap", "..."))
        self.pcapdstip.setText(_translate("readpcap", "目的IP地址"))
        self.pcapfilter.setText(_translate("readpcap", "查看过滤后数据包"))
        self.pcaptodisplay.setText(_translate("readpcap", "确认"))
        self.pcapip.setText(_translate("readpcap", "IP"))
        self.label_4.setText(_translate("readpcap", "协议"))
        self.label.setText(_translate("readpcap", "文件："))
        self.pcapdstport.setText(_translate("readpcap", "目的端口"))
        self.pcapdata.setText(_translate("readpcap", "数据片段"))
        self.pcapicmp.setText(_translate("readpcap", "ICMP"))
        self.label_2.setText(_translate("readpcap", "包过滤"))
        self.pcapsrcip.setText(_translate("readpcap", "源IP地址"))
        self.label_3.setText(_translate("readpcap", "选择要发送的数据包编号："))

